FROM localhost:5000/infra_ubuntu
MAINTAINER = Ruedi Steinmann <ruediste@gmail.com>

# download first, the more volatile aspects come later
RUN apt-get install -y  --no-install-recommends openjdk-7-jdk openjdk-7-jre-headless
RUN apt-get clean

